---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: acm-cloud
spec:
  destroyResourcesOnDeletion: false # We want to keep it and restore its tfstate
  interval: 8m
  path: ./
  sourceRef:
    kind: GitRepository
    name: terraform-aws-acm
    namespace: flux-system
  vars:
    - name: subject_alternative_names
      value:
        - "*.${domain_name}"
    - name: wait_for_validation
      value: true
    - name: tags
      value:
        Name: "${domain_name}"
  varsFrom:
    - kind: Secret
      name: route53-cloud-hostedzone
  writeOutputsToSecret:
    name: acm-cloud
