---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-config
  namespace: flux-system
spec:
  prune: true
  interval: 4m0s
  path: ./flux-config/controlplane-0
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      domain_name: "cloud.ogenki.io"
    substituteFrom:
      - kind: ConfigMap
        name: eks-controlplane-0-vars
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: capacitor
      namespace: flux-system
