apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/sealed-secrets

patches:
  - path: helmrelease.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: sealed-secrets
      namespace: kube-system
      version: v2beta1
