apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  chart:
    spec:
      sourceRef:
        kind: GitRepository
        name: tofu-controller
      chart: "./charts/tf-controller"
  interval: 1h0s
  releaseName: tofu-controller
  targetNamespace: flux-system
  install:
    crds: Create
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    replicaCount: 3
    concurrency: 24
    allowBreakTheGlass: true
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 400m
        memory: 64Mi
    caCertValidityDuration: 24h
    certRotationCheckFrequency: 30m
    runner:
      grpc:
        maxMessageSize: 30
    branchPlanner:
      enabled: true
