apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
spec:
  releaseName: aws-load-balancer-controller
  chart:
    spec:
      chart: aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: kube-system
      version: "1.5.3"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    clusterName: "${cluster_name}"
    serviceAccount:
      # Has to match the policy created using terraform (IRSA)
      name: aws-load-balancer-controller
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::${aws_account_id}:role/alb_controller_${cluster_name}"
    defaultTags:
      billing: k8s
      environment: "${environment}"
    replicaCount: 1
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    # vpcId: vpc-0695fe84adadbdf12
