apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: demo-tofu-controller
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/Smana/demo-tofu-controller
