apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security
  namespace: flux-system
spec:
  prune: true
  interval: 4m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./security/dev-hiving-bee
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: external-secrets
      namespace: kube-system
