apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: epi-external-secrets
spec:
  approvePlan: auto
  destroyResourcesOnDeletion: true
  interval: 8m
  sourceRef:
    kind: GitRepository
    name: terraform-aws-eks-pod-identity
    namespace: flux-system
  vars:
    - name: name
      value: external-secrets
    - name: attach_external_secrets_policy
      value: true
    - name: external_secrets_create_permission
      value: true
    - name: associations
      value:
        epi:
          cluster_name: ${cluster_name}
          namespace: security
          service_account: external-secrets
