apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/flux-iac/tofu-controller
