---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-config
  namespace: flux-system
spec:
  prune: true
  interval: 4m0s
  path: ./flux-config/controller-0
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: eks-controller-0-vars
        optional: true
      - kind: Secret
        name: eks-controller-0-vars
        optional: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: weave-gitops
      namespace: flux-system
