---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  prune: true
  interval: 4m0s
  path: ./infrastructure/controller-0/terraform/controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: true
      - kind: Secret
        name: cluster-vars
        optional: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: tf-controller
      namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tf-controller-custom-resources
  namespace: flux-system
spec:
  prune: true
  interval: 4m0s
  path: ./infrastructure/controller-0/terraform/custom-resources
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: eks-controller-0-vars
        optional: true
      - kind: Secret
        name: eks-controller-0-vars
        optional: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: tf-controller
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  prune: true
  interval: 4m0s
  path: ./infrastructure/controller-0
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: eks-controller-0-vars
        optional: true
      - kind: Secret
        name: eks-controller-0-vars
        optional: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: tf-controller-custom-resources
