---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: irsa-external-secrets
spec:
  approvePlan: auto
  destroyResourcesOnDeletion: true
  interval: 8m
  path: ./modules/iam-role-for-service-accounts-eks
  sourceRef:
    kind: GitRepository
    name: terraform-aws-iam
    namespace: flux-system
  vars:
    - name: role_name
      value: ${cluster_name}-external-secrets
    - name: attach_external_secrets_policy
      value: true
    - name: oidc_providers
      value:
        main:
          provider_arn: ${oidc_provider_arn}
          namespace_service_accounts: ["security:external-secrets"]
