apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: terraform-demo-tf-controller
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/Smana/demo-tf-controller
