apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack-grafana-admin
  namespace: temporal
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: observability/kube-prometheus-stack/grafana-admin
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: clustersecretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: kube-prometheus-stack-grafana-admin
